### PR TITLE
build: Fix clean target

### PR DESCRIPTION
**Pull request by ighvh**
Running `make clean` on an already cleaned working dir fails because config.mk cannot be found.

```
root@8579ec95b724:/linuxcnc-ethercat# dpkg-buildpackage -us -uc
dpkg-buildpackage: info: source package linuxcnc-ethercat
dpkg-buildpackage: info: source version 0.9.16
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Scott Laird <scott@sigkill.org>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 debian/rules clean
dh clean 
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   dh_auto_clean
dh_auto_clean: warning: Compatibility levels before 10 are deprecated (level 9 in use)
        make -j1 clean
make[1]: Entering directory '/linuxcnc-ethercat'
make[2]: Entering directory '/linuxcnc-ethercat/src'
make[3]: Entering directory '/linuxcnc-ethercat/src/devices'
Makefile:1: ../../config.mk: No such file or directory
make[3]: *** No rule to make target '../../config.mk'.  Stop.
make[3]: Leaving directory '/linuxcnc-ethercat/src/devices'
make[2]: *** [Makefile:16: clean] Error 2
make[2]: Leaving directory '/linuxcnc-ethercat/src'
make[1]: *** [Makefile:7: clean] Error 2
make[1]: Leaving directory '/linuxcnc-ethercat'
dh_auto_clean: error: make -j1 clean returned exit code 2
make: *** [debian/rules:13: clean] Error 255
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
```

### CODE REVIEW

**Review by scottlaird — COMMENTED** [review]
Ah, good catch.  I've been doing everything from inside of `src/`, so `make clean` doesn't end up deleting `config.mk`.

It feels kind of weird to have `make clean` build files, though.  I *think* we can mostly fix this by removing the `-` at the beginning of `-include ../config.mk` in `src/Makefile`.  We'll get an error after running `make clean` repeatedly, but that's better than hanging, which is what happens for me right now.

**Comment by scottlaird** [comment]
> Ah, good catch. I've been doing everything from inside of `src/`, so `make clean` doesn't end up deleting `config.mk`.
> 
> It feels kind of weird to have `make clean` build files, though. I _think_ we can mostly fix this by removing the `-` at the beginning of `-include ../config.mk` in `src/Makefile`. We'll get an error after running `make clean` repeatedly, but that's better than hanging, which is what happens for me right now.

Weirdly, without `config.mk`, the `Makefile` in `src/` seems to be calling `make` recursively.  That's odd, because there isn't a recursive call to make there.

Ah!  I see -- `-include $(MODINC)` without `config.mk` ends up just being `-include`, which presumably includes the Makefile over and over again.

It looks like removing the `-` from `-include $(MODINC)` but leaving the `-include ../config.mk` fixes everything.  Want to update this PR to do that?

**Comment by ighvh** [comment]
Actually, `make clean` generated a lot of .d files, too.

To avoid this in general, I moved the `clean` target into a separate Makefile.

**Review by scottlaird — APPROVED** [review]
This just feels ugly, but I can't find a better way to do this without side effects that are even worse.

**Pull request merged**
